name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  cd auth && docker build -t prabahal/auth .
      - uses: docker/login-action@v1
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push prabahal/auth
      - uses: digitalocean/action-dictl@v1
        with:
          token: ${{ DIGITALOCEAN_ACCESS_TOKEN }}
    
      
